// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLink: typeof import('./src/components/AppLink.vue')['default']
    DetailsBase: typeof import('./src/components/details/Base.vue')['default']
    DetailsDoc: typeof import('./src/components/details/Doc.vue')['default']
    DetailsGuide: typeof import('./src/components/details/Guide.vue')['default']
    DetailsResult: typeof import('./src/components/details/Result.vue')['default']
    DetailsRule: typeof import('./src/components/details/Rule.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ItemBase: typeof import('./src/components/item/Base.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    ListResources: typeof import('./src/components/ListResources.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Plum: typeof import('./src/components/Plum.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    ResultItem: typeof import('./src/components/ResultItem.vue')['default']
    RiMoonLine: typeof import('~icons/ri/moon-line')['default']
    RiSunLine: typeof import('~icons/ri/sun-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    SubNav: typeof import('./src/components/SubNav.vue')['default']
    Summary: typeof import('./src/components/Summary.vue')['default']
    TeamMembers: typeof import('./src/components/TeamMembers.vue')['default']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
  }
}
